// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tayxbbpyxbomiatbiirx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRheXhiYnB5eGJvbWlhdGJpaXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0NjA1NzcsImV4cCI6MjA5MTAzNjU3N30.FEVnZ_4AyZjZXBM9ZQtcfO2KBcIodCxaLD1l5yD4CXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});